theme: null
permalink: /:title
exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "node_modules"
  - "vendor/bundle/"
  - "vendor/cache/"
  - "vendor/gems/"
  - "vendor/ruby/"
  - "LICENSE"
kramdown:
  smart_quotes: ["apos", "apos", "quot", "quot"]
